name: Hello World
on: push
jobs:
  action-demo:
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
        - uses: actions/checkout@v4

        - name: printing the contents of index.html
          run: cat index.html

